### PR TITLE
Made the NME Project template more FlashDevelop-like

### PR DESCRIPTION
**Pull request by atomicptr**

### CODE REVIEW

**Comment by jgranick** [comment]
How do you feel about the NMML being named after the project, or having a consistent file name?

When I made the first FlashDevelop template for NME, I used the project name. Eventually Philippe implemented his own, and used "application.nmml" instead.

If we went with a consistent name, my vote would be for "project.nmml" instead, but I'm open to suggestions. My first thought was the project name, like "nme test MyGame.nmml mac"

Do you think there is a value in checking for Event.ADDED_TO_STAGE in each project? I feel that the default NMML and class files for the current FlashDevelop template are a bit of a mess. I like the simplicity of a clean slate.

If it is necessary to check for ADDED_TO_STAGE on iOS, for example, then perhaps we need to do something inside NME to make things work more nicely, so this is no longer required.

**Comment by atomicptr** [comment]
I would love to have a consistent name like "application.nmml", "build.nmml" or "project.nmml". I work mostly with command line tools and think it's much easier to do it like that. This is very similar to makefiles, did you ever call a makefile like the project? (Off-topic: with a consistent nmml file name we may could also use a default operation with the nme command line tool like: "nme test flash" which would run "nme test project.nmml flash", just a thought ;) ).

At the moment we need this event in each project, but of course it would be better to solve this in NME.

It's always better to start with less code.

**Comment by rynti** [comment]
I'll have to admit, a consistent name that is supported by NME (so you can avoid explicitly naming the .nmml file) would be quite handy.

About which name, I'd actually also go for "project.nmml" as it contains project properties. However, FlashDevelop would have to follow that and rename application.nmml to project.nmml in their template, too.

**Comment by jgranick** [comment]
This is a good idea.

While we're talking about names, what do you guys recommend for where to store the build number? Some platforms need the build number to be unique (and incrementing) when signing for a release. It also is used for many platforms to handle the "true" version of the application.

At first I used ".build" but someone suggested it might not go into version control, and may be overlooked or deleted. One other idea is to put it in the output directory, with no extension, like "Export/build" or "Export/buildId"

Do you guys have an opinion?

I am starting to like the idea of skipping the NMML name entirely, as an option. Could also work for directory paths, such as "nme test ~/Projects/Games/Pirate\ Pig flash"

What is the benefit of the ADDED_TO_STAGE event? Is the problem that the stage width/height is incorrect when it is first initialized?

**Comment by jgranick** [comment]
I just added support to NME for a default "project.nmml" or "project.xml" file.

Now the following are valid:

nme test project.nmml flash
nme test flash
nme test folder/to/project flash

**Comment by jgranick** [comment]
I also updated the add-in to use "project.nmml" by default

**Comment by jgranick** [comment]
I also updated NME on SVN/GIT so that it waits for the ADDED_TO_STAGE event for iOS, so that the stage size is correct. Thanks for your help!

**Pull request closed without merging**
